const COUNTRY_CODES = { "Singapore": "SIN", "Kualalumpur": "KUL", "SanFransisco": "SFO" }
    , FETCH_COUNTRY = "FETCH_COUNTRY"
    , FETCH_LANGLOC = "FETCH_LANGLOC"
    , SELECT_ROUTE = "SELECT_ROUTE"
    , FETCH_CHEAPEST_PRICE = "FETCH_CHEAPEST_PRICE"
    , CALENDAR_LOADING_STATUS = "CALENDAR_LOADING_STATUS"
    , FETCHING_ERROR = "FETCHING_ERROR"
    , LOADING_WAIT = "Loading Calendar Data. Please Wait..."

module.exports = {
    COUNTRY_CODES
  , FETCH_COUNTRY
  , FETCH_LANGLOC
  , SELECT_ROUTE
  , FETCH_CHEAPEST_PRICE
  , CALENDAR_LOADING_STATUS
  , FETCHING_ERROR
  , LOADING_WAIT
}